### ISSUE TITLE
RSA_KEY_ADD 和 RSA_KEY

### ISSUE THREAD

**Issue by BROBIRD** [ymback/Battle.net-Authenticator-Online#2]
哪一个填公钥，哪一个填私钥？我自己搭建的站点总是卡死，并提示
`Error: Script terminated by timeout at:
biSubtract@https://***/resources/js/rsa.js:1:4269
BarrettMu_modulo@https://***/resources/js/rsa.js:2:693
BarrettMu_multiplyMod@https://***/resources/js/rsa.js:2:830
BarrettMu_powMod@https://***/resources/js/rsa.js:2:1069
encryptedString@https://***/resources/js/rsa.js:3:1543
submitcheck@https://***/register.php:81:21
onclick@https://***/register.php:1:19
`

**Comment by ymback** [comment]
ADD填私钥的KEY文件地址，还有个填公钥

**Comment by BROBIRD** [comment]
公钥也是文件地址吗？还是文件内容？谢谢
